# Generated by Django 5.0.14 on 2025-08-14 03:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
